.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.TH MUGSHOT "1" "August 2018" "mugshot 0.4" "User Commands"
.SH NAME
mugshot \- lightweight user configuration utility
.SH DESCRIPTION
Mugshot is a lightweight user configuration utility. Mugshot allows you to easily set profile image and user details for your user profile and any supported applications.
.SH SYNOPSIS
.B mugshot
[\fIoptions\fR]
.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Show debug messages (\fB\-vv\fR debugs mugshot_lib also)
.SH "SEE ALSO"
The full documentation for
.B mugshot
is maintained online at
.URL "https://wiki.bluesabre.org/doku.php?id=mugshot-docs" "the authors documentation portal" "."
.SH BUGS
Please report bugs at
.URL "https://bugs.launchpad.net/mugshot" "the Mugshot Bugs page" "."
.SH AUTHOR
Sean Davis (smd.seandavis@gmail.com)
