.TH "mugshot" "1"
.SH "NAME"
mugshot \- A lightweight user-configuration application
.SH "SYNOPSIS"
\fB
.SH "DESCRIPTION"
.B mugshot
allows you to easily update personal user details, including finger 
information, Pidgin buddy icon, and LibreOffice user details.
.SH "AUTHOR"
.PP
This manual page was written by Sean Davis <smd.seandavis@gmail.com> 
for the \fBDebian GNU/Linux\fP system.


